columnSuffix: xqpmplpe
contentColumnType: text
fieldGroup: 4579a2df-4698-436d-81c2-092ce5a5c11f # Company
handle: city
instructions: null
name: City
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
