columnSuffix: dtkvoabc
contentColumnType: text
fieldGroup: a72f3aef-9c28-4bcc-98fb-578f8dccf5d7 # Posts
handle: generalId
instructions: null
name: 'General ID'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
